name: "🧪 Unit Tests"

on:
  workflow_call:
    inputs:
      project_name:
        description: 'A project name passed from the caller workflow'
        required: true
        type: string

defaults:
  run:
    shell: pwsh

jobs:
  Test_Communicator_Sln:
    name: "🧪 Test Project Solution"
    run-name: "🧪 Test ${{ inputs.project_name }}.sln"
    if: ${{ always() }}
    runs-on: self-hosted
    steps:
    - name: "🚚 Get Latest Code"
      uses: actions/checkout@v3
    - name: ⚙️ Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: "16"
    - name: ⚙️ Use .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: "🚧 Restore Dependencies"
      run: dotnet restore
    - name: "🛠️ Build"
      run: dotnet build --no-restore
    - name: "🧪 Test"
      run: |
        dotnet test --no-build --no-restore --verbosity normal --filter Category!=Integration --settings CodeCoverage.runsettings -r ./CodeCoverage
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator -reports:CodeCoverage/**/coverage.info -targetdir:CodeCoverage -reporttypes:lcov
    - name: "👖 Coveralls"
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./CodeCoverage/lcov.info
        flag-name: ${{ inputs.project_name }}.sln
